server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: game-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/game_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/xo-realm}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.xogame.game_service: DEBUG

